{% set name = "aleph-alpha-client" %}
{% set version = "3.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aleph-alpha-client-{{ version }}.tar.gz
  sha256: 188e9c70e58edb6f31d77c58d7963ba1427a42be68f8f40beff6ff76d407c10a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.28
    - urllib3 >=1.26
    - aiohttp >=3.8.3
    - aiodns >=3.0.0
    - aiohttp-retry >=2.8.3
    - tokenizers >=0.13.2
    - typing-extensions >=4.5.0
    - pillow >=9.2.0

test:
  imports:
    - aleph_alpha_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Aleph-Alpha/aleph-alpha-client
  summary: python client to interact with Aleph Alpha api endpoints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdejager
