{% set name = "aleph-alpha-client" %}
{% set version = "3.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aleph-alpha-client-{{ version }}.tar.gz
  sha256: 4699210b2eb3d612cc4fe1a9faefd20f01e73f4671aaec793f700c962b7f32b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - requests >=2.28
    - urllib3 >=1.26
    - aiohttp >=3.8.3
    - aiodns >=3.0.0
    - aiohttp-retry >=2.8.3
    - tokenizers >=0.13.2
    - typing-extensions >=4.5.0
    - pillow >=9.2.0

test:
  imports:
    - aleph_alpha_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Aleph-Alpha/aleph-alpha-client
  summary: python client to interact with Aleph Alpha api endpoints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdejager
